name: AuthMe
author:  Fabe & Pomo4ka & Whoami
description: AuthMe prevents people, which aren't logged in, from doing stuff like placing blocks, moving, typing commands or seeing the inventory of the current player.
version: 0.85
main: de.fgtech.pomo4ka.AuthMe.AuthMe
commands:
    login:
        description: With this command a player can login!
        usage:
        aliases: l
    register:
        description: With this command a player can register!
        usage:
    changepassword:
        description: With this command you can change your password!
        usage:
    logout:
        description: With this command a player can logout!
        usage:
    unregister:
        description: With this command you can delete your account!
        usage:
    authme:
        description: General command for Ops to control AuthMe!
        usage: